### ISSUE TITLE
Missing objects :PartyConsent EngagementChannelType CommSubscription CommSubscriptionChannelType CommSubscriptionConsent CommSubscriptionTiming

### ISSUE THREAD

**Issue by ppavliv** [Patlatus/BofPerMan#4]
The following objects 

- PartyConsent
- EngagementChannelType
- CommSubscription
- CommSubscriptionChannelType
- CommSubscriptionConsent
- CommSubscriptionTiming

are missing from Object selection dropdown

**Comment by ppavliv** [comment]
![MissingObjects](https://user-images.githubusercontent.com/62899252/77937519-21d1bb80-72bd-11ea-9c17-7fa82d498fc2.png)

**Comment by Patlatus** [comment]
I can confirm that many objects that are available to set Object Level Security in Profile and Permission Set standard Salesforce interface, are not listed  in the package. This is because they are not in the Global Describe list. I need to maintain a list of fake describe to match up those.

Alternative Payment Methods
API Anomaly Event Stores
Asset Actions
Asset Action Sources
Asset State Periods
Card Payment Methods
Communication Subscriptions
Communication Subscription Channel Types
Communication Subscription Consents
Communication Subscription Timings
Credential Stuffing Event Stores
Credit Memos
Digital Wallets
Employees
Engagement Channel Types
Finance Balance Snapshots
Finance Transactions
Gateway Provider Payment Method Types
Internal Organization Units
Invoices
Legal Entities
Party Consents
Payments
Payment Authorizations
Payment Authorization Adjustments
Payment Gateways
Payment Gateway Logs
Payment Groups
Payment Line Invoices
Refunds
Refund Line Payments 
Report Anomaly Event Stores
Session Hijacking Event Stores

**Comment by Patlatus** [comment]
API Anomaly Event Store is available in the EntityDefinition list

**Comment by Patlatus** [comment]
AccountBrand, AccountForecast, AccountRelationship, Accreditation, AcctMgrTarget, ActionCadence, ActionCadenceStep, ActionCadenceStepTracker, ActionCadenceTracker, ActionPlan, ActionPlanTemplate, ActivationPlatform, ActivationTarget, ActivationTrgtIntOrgAccess, ActiveScratchOrg, ActivityTiming, AdCreativeSizeType, AddOnDefinition, AdOrderItem, AdQuote, AdQuoteLine, AdServer, AdServerAccount, AdServerUser, AdSpaceCreativeSizeType, AdSpaceGroupMember, AdSpaceSpecification, AdvAccountForecastFact, AdvAcctForecastFactAdj, AdvAcctForecastSetPartner, AgentTraining, AggregationRow, AiDataset, AiImageDetectedObject, AiImageTrainingObject, AirTravelEmssnFctr, AirTravelEnrgyUse, AISentimentResult, AiVisionModel, AiVisionModelMetric, AiVisionModelObjectMetric, AiVisitRecommendation, AiVisitRecommendRequest, AiVisitSummary, AiVisitTaskRcmd, AiVisitTaskRcmdRequest, AllergyIntolerance, AnalyticsDatabase, AnalyticsSchema, AnalyticsTable, ApplicationCase, AppointmentReason, AppointmentScheduleAggr, AppointmentScheduleLog, ApptAssignmentRsrcPool, ApptBundleAggrDurDnscale, ApptBundleAggrPolicy, ApptBundleConfig, ApptBundlePolicy, ApptBundlePolicySvcTerr, ApptBundlePropagatePolicy, ApptBundleRestrictPolicy, ApptBundleSortPolicy, Assessment, AssessmentIndDefinedValue, AssessmentIndicatorDefinition, AssessmentIndValue, AssessmentQuestion, AssessmentQuestionResponse, AssessmentQuestionSet, AssessmentQuestionVersion, AssessmentTask, AssessmentTaskContentDocument, AssessmentTaskDefinition, AssessmentTaskIndDefinition, AssessmentTaskOrder, AssetAttribute, AssistantText, AssistantTextRange, Assortment, AssortmentProduct, AttributeDefinition, AuthApplicationAsset, AuthApplicationPlace, AuthLocationAccessSchedule, AuthorizedInsuranceLine, AuthorNote, Award, Banker, Benefit, BenefitParameterValue, BenefitType, BillingBatchScheduler, BillingPeriodItem, BillingPeriodTaxItem, BillingPolicy, BillingSchedule, BillingScheduleCreationStatus, BillingScheduleGroup, BillingTreatment, BillingTreatmentItem, BldgEnrgyIntensity, BldgEnrgyIntensityVal, BldgSizeCategory, BlockchainEvent, BoardCertification, BranchUnit, BranchUnitBusinessMember, BranchUnitCustomer, Budget, BudgetAllocation, BusinessBrand, BusinessLicense, BusinessLicenseApplication, BusinessMilestone, BusinessProfile, BusinessType, BusRegAuthorizationType, BusRegAuthTypeDependency, BuyerAccount, BuyerGroup, BuyerGroupPricebook, CalcProcStepRelationship, CalculationMatrix, CalculationMatrixColumn, CalculationMatrixRow, CalculationMatrixVersion, CalculationProcedure, CalculationProcedureStep, CalculationProcedureVariable, CalculationProcedureVersion, CareBarrier, CareBarrierDeterminant, CareBarrierType, CareBenefitVerifyRequest, CareDeterminant, CareDeterminantType, CareDiagnosis, CareInterventionType, CareMetricTarget, CareObservation, CareObservationComponent, CarePerformer, CarePgmProvHealthcareProvider, CarePractnFacilityAppt, CarePreauth, CarePreauthItem, CareProgram, CareProgramCampaign, CareProgramEligibilityRule, CareProgramEnrollee, CareProgramEnrolleeProduct, CareProgramEnrollmentCard, CareProgramGoal, CareProgramProduct, CareProgramProvider, CareProgramTeamMember, CareProviderAdverseAction, CareProviderFacilitySpecialty, CareProviderSearchableField, CareRegisteredDevice, CareRequest, CareRequestDrug, CareRequestExtension, CareRequestItem, CareRequestReviewer, CareSpecialty, CareSpecialtyTaxonomy, CareTaxonomy, Certification, CertificationDef, CertificationSectionDef, CertificationStep, CertificationStepDef, ChangeRequest, ChannelProgram, ChannelProgramLevel, ChannelProgramMember, Claim, ClaimCase, ClaimCoverage, ClaimCoveragePaymentDetail, ClaimCoverageReserveDetail, ClaimCovPaymentAdjustment, ClaimCovReserveAdjustment, ClaimItem, ClaimParticipant, ClaimPaymentSummary, ClinicalAlert, ClinicalEncounter, ClinicalEncounterDiagnosis, ClinicalEncounterFacility, ClinicalEncounterIdentifier, ClinicalEncounterProvider, ClinicalEncounterReason, ClinicalEncounterSvcRequest, ClinicalServiceRequest, ClinicalServiceRequestDetail, CloudServiceProvider, CloudServiceProviderApi, CodeSet, CodeSetBundle, CollabMonitoringInstance, CommerceCustomer, CommerceEntitlementPolicy, CommerceGuestOrder, CommerceOrderCustomer, CommissionSchedule, CommissionScheduleAssignment, ComplaintCase, ContactEncounter, Coupon, CourseOffering, CoverageBenefit, CoverageBenefitItem, CoverageBenefitItemLimit, CoverageType, CrbnEmssnScopeAlloc, CrbnEmssnScopeAllocVal, Crisis, Customer, CustomerProperty, DataAction, DataActionCondition, DataActionDataActnTgtDef, DataActionDefinition, DataActionField, DataActionSourceObject, DataActionTarget, DataActionTargetDefinition, DataConnectionGcs, DataConnectorCC, DataConnectorCredential, DataConnectorGcs, DataConnectorIngestApi, DataConnectorMC, DataConnectorS3, DataConnectorSftp, DataConnectorUpload, DataConnInteractionStudio, DataLakeObjectInstance, DataModelRelationConstraint, DataModelTaxonomy, DataModelVersion, DataObjectCategory, DataPackageKit, DataPackageKitDefinition, DataPackageKitObject, DataPlatform, DataSource, DataSourceBundle, DataSourceBundleDefinition, DataSourceField, DataSourceObject, DataSourceTenant, DataSrcDataModelFieldMap, DataStream, DataStreamDefinition, DataStreamTemplate, DefinedSkill, DelegatedAccount, DeliveryTask, DiagnosticSummary, DiagnosticSummaryDetail, DistributorAuthorization, DocumentChecklistItem, DocumentGenerationProcess, DocumentRecipient, DocumentTemplate, DocumentTemplateClause, DrugDisplayTerm, EditionDefinition, ElectricityEmssnFctrSet, ElectronicMediaGroup, Employee, EmployeeAsset, EmployeeContact, EmployeeCrisisAssessment, EmployeeJob, EmployeeJobPosition, EngagementProgram, EngagementProgramNode, EngagementProgramVersion, EnrolleeBenefit, EnrollmentEligibilityCriteria, EnvironmentHubInvitation, EnvironmentHubMember, Examination, ExternalAccountHierarchy, ExternalDataConnector, ExternalDataTranField, ExternalDataTranObject, FieldSrcTrgtRelationship, FinanceBook, FinanceTransactionErrorLog, FinancialDeal, FinancialDealInteraction, FinancialDealParty, FinancialDealProduct, FinclDealInteractionSummary, FrgtHaulingEmssnFctr, FrgtHaulingEnrgyUse, FtestAccountChild, FtestBigObjectLookup, FtestChild, FtestChildConcrete, FtestConcrete, FtestConcrete2, FtestConcrete3, FtestConcrete4, FtestConcrete5, FtestConcrete6, FtestConcrete7, FtestConcrete8, FtestConcreteNoDefault, FtestConcreteNoDefault2, FtestConcreteNoDefault3, FtestConcreteNoSup, FtestConcreteNoSup2, FtestConcreteNoSup3, FtestContactPointEmail, FtestContactPointPhone, FtestDerivedMain, FtestEntityFieldFamilyBase, FtestError, FtestErrorChild, FtestGrandChild, FtestHiddenName, FtestMain, FtestOffCoreRecord, FtestPerson, FTestStandardEventHV, FtestTopLevelWithCrud, FtestVirtualMain, FulfillmentOrder, FunctionInvocationRequest, GeneratedDocument, GeneratedWaste, GenericVisitTask, GenericVisitTaskContext, GnrcVstKeyPerformanceInd, GnrcVstTaskContextRelation, GroundTravelEmssnFctr, GroundTravelEnrgyUse, HealthCareDiagnosis, HealthcareFacility, HealthcareFacilityNetwork, HealthcarePayerNetwork, HealthcarePractitionerFacility, HealthCareProcedure, HealthcareProvider, HealthcareProviderNpi, HealthcareProviderSpecialty, HealthcareProviderTaxonomy, HealthCondition, HealthConditionDetail, HotelStayEmssnFctr, HotelStayEnrgyUse, Household, IdeaTheme, Identifier, IdentityDocument, IdentityResolution, IdentityResolutionDefinition, IdentityResolutionMatchRule, IdentityResolutionRecon, IdRsolDataMdlObjFieldRel, IdRsolDataModelObject, IdRsolMatchRuleCriteria, IdRsolReconFieldRel, IdRsolReconFieldRule, IdRsolReconObjectRule, IdRsolReconObjRuleFldSet, IdRsolReconRuleDataLkObj, Incident, IncludedLicenseDefinition, IndividualApplication, InflationRate, InfoAuthorizationRequest, InspectionAssessmentInd, InspectionType, InspectionViolation, InStoreLocation, InsuranceClaimAsset, InsurancePolicy, InsurancePolicyAsset, InsurancePolicyCoverage, InsurancePolicyMemberAsset, InsurancePolicyParticipant, InsurancePolicySurcharge, InsurancePolicyTransaction, InsuranceProfile, Interaction, InteractionAttendee, InteractionSumDiscussedAccount, InteractionSummary, InternalDataConnector, InternalOrganization, InternalOrganizationUnit, JobFamily, JobPosition, JobRole, JournalSubType, JournalType, LearnerSkill, LicensingError, LicensingRequest, LicensingSnapshotRequest, LiveAgentSession, LiveChatTranscript, LiveChatVisitor, LoanApplicant, LoanApplicantAddress, LoanApplicantAsset, LoanApplicantDeclaration, LoanApplicantEmployment, LoanApplicantIncome, LoanApplicantLiability, LoanApplicationAsset, LoanApplicationFinancial, LoanApplicationLiability, LoanApplicationProperty, LoanApplicationTitleHolder, LocationTrustMeasure, LocationWaitlist, LocationWaitlistedParty, LocWaitlistMsgTemplate, LoyaltyLedger, LoyaltyMemberCurrency, LoyaltyMemberTier, LoyaltyPartnerProduct, LoyaltyPgmGroupMbrRlnsp, LoyaltyProgram, LoyaltyProgramCurrency, LoyaltyProgramMbrPromotion, LoyaltyProgramMember, LoyaltyProgramMemberCase, LoyaltyProgramPartner, LoyaltyTier, LoyaltyTierBenefit, LoyaltyTierGroup, ManagementAddOnLicense, ManagementEditionLicense, ManagementPlatformLicense, ManagementUserLicense, MarketSegment, MarketSegmentActivation, MarketSegmentField, MasterPrflDataSrcLineage, MediaChannel, MediaContentTitle, Medication, MedicationRequest, MedicationStatement, MedicinalIngredient, MemberBenefit, MemberPlan, MessagingEndUser, MessagingSession, MktCalcInsightObjectDef, MktCalculatedInsight, MktCalculatedInsightField, MktCalculatedInsightObject, MktDataLakeField, MktDataLakeObject, MktDataModelField, MktDataModelObject, MktDataTranField, MktDataTranObject, MktSgmntActvtnAudAttribute, MktSgmntActvtnContactPoint, MktSgmtActvContactPtField, MktSgmtActvContactPtSrc, MultipartyInfoAuthRequest, NamespaceRegistry, NetworkReferencedObject, ObjectSourceTargetMap, ObjectStateDefinition, ObjectStateTransition, ObjectStateValue, OccupationLicenseApplication, OcrDocumentScanResult, OmniDataPack, OmniDataTransform, OmniDataTransformItem, OmniESignatureTemplate, OmniProcess, OmniProcessCompilation, OmniProcessElement, OmniProcessTransientData, OmniScriptSavedSession, OmniUiCard, OrderDeliveryMethod, OrderSummary, OrderSummaryRoutingSchedule, OrgSnapshot, OtherComponentTask, OtherEmssnFctrSet, OtherEmssnFctrSetItem, PartnerFundAllocation, PartnerFundClaim, PartnerFundRequest, PartnerMarketingBudget, PartyIdMatchRuleCriteria, PartyIncome, PartyMatchRule, PartyMatchRuleCriteria, PartyReconRule, PartyReconRuleSeq, PartyRelatedParty, PartyRelationshipType, PatientApiRecordLock, PatientHealthReaction, PatientImmunization, PatientMedicalProcedure, PatientMedicalProcedureDetail, PatientMedicationDosage, PaymentApplicationMethod, PaymentBatchRun, PaymentBatchRunCriteria, PaymentPolicy, PaymentSchedule, PaymentScheduleItem, PaymentTerm, PaymentTreatment, PcmtEmssnFctrSet, PcmtEmssnFctrSetItem, PersonalDevelopmentPlan, PersonEducation, PersonEmployment, PersonExamination, PersonLanguage, PersonLifeEvent, PersonList, PersonName, PgmRebateTypBnftMapping, PlanBenefit, PlanBenefitItem, PlatformLicenseDefinition, Polygon, PreliminaryApplicationRef, PriceAdjustmentSchedule, Problem, Producer, ProducerCommission, ProducerPolicyAssignment, ProductAvailabilityProjection, ProductCatalog, ProductCategory, ProductCategoryProduct, ProductCoverage, ProductFulfillmentLocation, ProductSellingModel, ProgramRebateType, ProgramRebateTypeBenefit, ProgramRebateTypeFilter, ProgramRebateTypePayout, ProgramRebateTypeProduct, ProgramRebateTypeReference, ProgramRebateTypPayoutSrc, Promotion, PromotionChannel, PromotionLoyaltyPtnrProdt, PromotionMarketSegment, PromotionProduct, PromotionProductCategory, PromotionQualifier, PromotionSegment, PromotionTarget, ProviderNetworkContract, ProviderNetworkTier, PublicComplaint, PublicProgram, PurchaseQuantityRule, PurchaserPlan, PurchaserPlanAssn, Question, Quote, RebateMemberProductAggregate, RebatePayment,

**Comment by Patlatus** [comment]
Looks like some objects are available in classic but not in Lightning, this is strange

**Comment by Patlatus** [comment]
AssetAction
AssetStatePeriod
BusinessBrand
CreditMemo
Customer
Invoice
Scorecard 3
Seller
